name: Run Specs

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Download source
        uses: actions/checkout@v2
      
      - name: Install Crystal
        uses: oprypin/install-crystal@v1.4.0
        with:
          crystal: latest

      - name: Build example
        run: crystal spec

      - name: Check formatting
        run: crystal tool format --check
